# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-ssosync
  description: Deploys AWS ssosync to sync Google Groups with AWS SSO
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component
